const pack = [
  { number: 4, naipe: 'ouro', weight: 1 },
  { number: 4, naipe: 'espada', weight: 1 },
  { number: 4, naipe: 'copas', weight: 1 },
  { number: 4, naipe: 'paus', weight: 1 },
  { number: 5, naipe: 'ouro', weight: 2 },
  { number: 5, naipe: 'espada', weight: 2 },
  { number: 5, naipe: 'copas', weight: 2 },
  { number: 5, naipe: 'paus', weight: 2 },
  { number: 6, naipe: 'ouro', weight: 3 },
  { number: 6, naipe: 'espada', weight: 3 },
  { number: 6, naipe: 'copas', weight: 3 },
  { number: 6, naipe: 'paus', weight: 3 },
  { number: 7, naipe: 'ouro', weight: 4 },
  { number: 7, naipe: 'espada', weight: 4 },
  { number: 7, naipe: 'copas', weight: 4 },
  { number: 7, naipe: 'paus', weight: 4 },
  { number: 8, naipe: 'ouro', weight: 5 },
  { number: 8, naipe: 'espada', weight: 5 },
  { number: 8, naipe: 'copas', weight: 5 },
  { number: 8, naipe: 'paus', weight: 5 },
  { number: 9, naipe: 'ouro', weight: 6 },
  { number: 9, naipe: 'espada', weight: 6 },
  { number: 9, naipe: 'copas', weight: 6 },
  { number: 9, naipe: 'paus', weight: 6 },
  { number: 10, naipe: 'ouro', weight: 7 },
  { number: 10, naipe: 'espada', weight: 7 },
  { number: 10, naipe: 'copas', weight: 7 },
  { number: 10, naipe: 'paus', weight: 7 },
  { number: 1, naipe: 'ouro', weight: 8 },
  { number: 1, naipe: 'espada', weight: 8 },
  { number: 1, naipe: 'copas', weight: 8 },
  { number: 1, naipe: 'paus', weight: 8 },
  { number: 2, naipe: 'ouro', weight: 9 },
  { number: 2, naipe: 'espada', weight: 9 },
  { number: 2, naipe: 'copas', weight: 9 },
  { number: 2, naipe: 'paus', weight: 9 },
  { number: 3, naipe: 'ouro', weight: 10 },
  { number: 3, naipe: 'espada', weight: 10 },
  { number: 3, naipe: 'copas', weight: 10 },
  { number: 3, naipe: 'paus', weight: 10 },
];

export default pack;
